version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - echo "started"
      - aws cloudformation package --template-file pdftotxt.yaml --s3-bucket open-search-docs --s3-prefix artifacts/ --output-template-file lambdaoutput.yaml
      - echo "cmplete"

artifacts:
  type: zip
  files:
    - pdftotxt.yaml
    - lambdaoutput.yaml