version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - echo "started"
      - aws cloudformation package --template-file pdf-to-text/pdftotxt.yaml --s3-bucket artifacts-bucket-gl --output-template-file lambdaoutput.yaml
      - echo "cmplete"

artifacts:
  type: zip
  files:
    - pdftotxt.yaml
    - lambdaoutput.yaml