AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::060795935152:role/open-search-lambda-fa'
      Environment:
        Variables:
          TARGET_BUCKET: open-search-docs/texts/
      Layers:
        - 'arn:aws:lambda:us-east-1:060795935152:layer:pypdf-layer:2'
